import Head from 'next/head';

import ExampleButton from '@/components/ExampleButton';
import useHelloWorldService from '@/src/hooks/services/useHelloWorldService';
import { IHelloWorldService } from '@/src/services/i-hello-world.service';

const Home = () => {
  const helloWorldService: IHelloWorldService = useHelloWorldService();

  const onSayHello = (): void => {
    helloWorldService.sayHello("John Doe");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid h-full place-items-center p-4">
        <div className="flex flex-col items-center justify-center gap-4">
          <h1 className="text-3xl font-semibold">Next.js Template</h1>
          <ExampleButton text="Click Me!" onClick={onSayHello} />
        </div>
      </div>
    </>
  );
};

export default Home;
